# play-server-configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: play-server-config
  labels:
    app: play-server
  namespace: {{ .Values.teamName }}
data:
  CLOUDFRONT_DOMAIN: {{ .Values.playServer.config.cloudFront.domain }}
  CLOUDFRONT_EXPIRE_TIME: {{ .Values.playServer.config.cloudFront.expireTime }}
  CORS_ALLOWED_ORIGINS: {{ .Values.playServer.corsAllowedOrigins }}
