{{- $ := .Values.mediamtxServer -}}
{{- $context := merge (dict "appName" $.appName "component" $.appName) . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neves.name.deploy" $context }}
  namespace: {{ .Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  replicas: {{ $.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "neves.name.app" $context | quote }}
  template:
    metadata:
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
    spec:
      containers:
      - name: {{ include "neves.name.container" $context }}
        image: "{{ $.image.repository }}:{{ $.image.tag }}"
        imagePullPolicy: {{ $.image.pullPolicy }}
        ports:
        - name: srt-port
          containerPort: {{ $.containerPorts.srt }}
          protocol: UDP
        - name: api-port
          containerPort: {{ $.containerPorts.api }}
          protocol: TCP
        volumeMounts:
          - name: config-volume
            mountPath: /mediamtx.yml
            subPath: mediamtx.yml
          - name: {{ $.persistence.volumeName }}
            mountPath: {{ $.persistence.mountPath }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "neves.name.configmap" $context }}
        - name: {{ $.persistence.volumeName }}
          persistentVolumeClaim:
            claimName: {{ $.persistence.existingClaim }}
