{{- $ := .Values.offlineUploadServer -}}
{{- $context := merge (dict "appName" $.appName "component" $.appName) . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neves.name.deploy" $context }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  replicas: {{ $.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "neves.name.app" $context | quote }}
  template:
    metadata:
      labels:
        {{- /* 파드 레벨의 레이블은 들여쓰기가 더 필요합니다. */}}
        {{- include "neves.commonLabels" $context | nindent 8 }}
    spec:
      containers:
      - name: {{ include "neves.name.container" $context }}
        image: "{{ .Values.image.root }}{{ $.image.repository }}:{{ $.image.tag }}"
        imagePullPolicy: {{ $.image.pullPolicy }}
        ports:
        - containerPort: {{ $.service.containerPort }}
        envFrom:
        - configMapRef:
            name: {{ include "neves.name.configmap" $context }}
        {{- if $.persistence.enabled }}
        volumeMounts:
          - name: {{ $.persistence.volumeName }}
            mountPath: {{ $.persistence.mountPath }}
        {{- end }}
      {{- /* 'volumes' 섹션은 'containers'와 동일한 레벨에 있어야 합니다. */}}
      {{- if $.persistence.enabled }}
      volumes:
        - name: {{ $.persistence.volumeName }}
          persistentVolumeClaim:
            claimName: {{ $.persistence.existingClaim }}
      {{- end }}

