{{- $ := .Values.offlineUploadServer -}}
{{- $context := merge (dict "appName" $.appName "component" $.appName) . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neves.name.deploy" $context }}
  namespace: {{ .Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  replicas: {{ $.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "neves.name.app" $context | quote }}
  template:
    metadata:
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
    spec:
      containers:
      - name: {{ include "neves.name.container" $context }}
        image: "{{ .Values.image.root }}{{ $.image.repository }}:{{ $.image.tag }}"
        imagePullPolicy: {{ $.image.pullPolicy }}
        ports:
        - containerPort: {{ $.service.containerPort }}
        envFrom:
        - configMapRef:
            name: {{ include "neves.name.configmap" $context }}
        volumeMounts:
          - name: {{ $.persistence.volumeName }}
            mountPath: {{ $.persistence.mountPath }}
      volumes:
        - name: {{ $.persistence.volumeName }}
          persistentVolumeClaim:
            claimName: {{ $.persistence.existingClaim }}

