apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server
  namespace: "{{  }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-server
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
      - name: user-server
        image: "{{  }}"
        envFrom:
        - secretRef:
            name: user-server-secret
        - configMapRef:
            name: user-server-config