{{ $context := merge (dict "app" $.Values.dbUploadServer) . -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
{{ with .Values.dbUploadServer.secret -}}
data:
  AWS_ACCESS_KEY_ID: {{ .aws.accessKeyId | b64enc | quote  }}
  AWS_SECRET_ACCESS_KEY: {{ .aws.secretAccessKey | b64enc | quote  }}
{{ end -}}
