{{- if .Values.dbUploadServer }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neves.name.secret" (dict
      "Values" .Values "Chart" .Chart "Release" .Release
      "appName" .Values.dbUploadServer.name
      "component" (.Values.dbUploadServer.component | default "batch")) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neves.commonLabels" (dict
        "Values" .Values "Chart" .Chart "Release" .Release
        "appName" .Values.dbUploadServer.name
        "component" (.Values.dbUploadServer.component | default "batch")) | nindent 4 }}
type: Opaque
stringData:
  aws-access-key-id: {{ default "" .Values.dbUploadServer.secret.awsAccessKeyId | quote }}
  aws-secret-access-key: {{ default "" .Values.dbUploadServer.secret.awsSecretAccessKey | quote }}
{{- end }}
