{{ $context := merge (dict "app" $.Values.mailServer) . -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
data:
{{- with .Values.mailServer.secret }}
  GMAIL_USER: {{ .gmail.user | b64enc | quote }}
  GMAIL_PASSWORD: {{ .gmail.password | b64enc | quote }}
{{ end -}}
