{{ $context := merge (dict "app" $.Values.playServer) . -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
data:
{{- with .Values.playServer.secret }}
  KEY_PAIR_ID: {{ .s3.keyPairId | b64enc | quote }}
  S3_PRIVATE_KEY: {{ .s3.privateKey | b64enc | quote }}
{{ end -}}
