{{ $context := merge (dict "app" $.Values.userServer) . -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
data:
{{- with .Values.userServer.secret }}
  DB_USER: {{ .db.username | b64enc | quote }}
  DB_PASSWORD: {{ .db.password | b64enc | quote }}
  PRIVATE_KEY: {{ .privateKey | b64enc | quote }}
  PUBLIC_KEY:  {{ .publicKey | b64enc | quote }}
{{ end -}}
