{{ $context := merge (dict "app" $.Values.userServer) . -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
data:
{{- with .Values.userServer.secret }}
  DB_USER: {{ .db.username }}
  DB_PASSWORD: {{ .db.password }}
{{ end -}}
