teamName: neves

url:
  domain:
    root: neves-box.com
    apiPrefix: api
    monitoringPrefix: mnt

image:
  root: public.ecr.aws/k8s0f8l3/neves/

status:
  name: status
  image:
    repo: status-service
    tag: latest
  config:
    db:
      url: ...