teamName: neves

url:
  domain:
    root: neves-box.com
    apiPrefix: api
    monitoringPrefix: mnt

image:
  root: public.ecr.aws/k8s0f8l3/neves/

statusServer:
  name: status
  image:
    repo: status-service
    tag: latest
  config:
    db:
      url: ...

dbUploadServer:
  name: db-upload
  image:
    repo: db-upload-server
    tag: dev
    pullPolicy: IfNotPresent
  replicas: 1
  ports:
    http: 8080
  config:
    aws:
      defaultRegion: ap-northeast-2
      s3BucketName: neves-video-bucket
  secret:
    awsAccessKeyId: "a"
    awsSecretAccessKey: "b"
  persistence:
    enabled: true
    name: shared-efs-storage
    mountPath: /recordings
    existingClaim: efs-shared-pvc