{{- $ := .Values.mediamtxServer -}}
{{- $context := merge (dict "appName" $.appName "component" $.appName) . -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "neves.name.svc" $context }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
  {{- with $.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $.service.type }}
  ports:
    - name: api-tcp
      port: {{ $.service.ports.api.port }}
      protocol: {{ $.service.ports.api.protocol }}
      targetPort: {{ $.service.ports.api.targetPort }}
    - name: srt-udp
      port: {{ $.service.ports.srt.port }}
      protocol: {{ $.service.ports.srt.protocol }}
      targetPort: {{ $.service.ports.srt.targetPort }}
  selector:
    app: {{ include "neves.name.app" $context | quote }}
