{{ $context := merge (dict "app" $.Values.mediamtxServer) . -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "neves.name.svc" $context }}
  namespace: {{ $.Values.teamName }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-name: streaming-lb
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  selector:
    app: {{ include "neves.name.app" $context }}
  type: LoadBalancer
  ports:
{{- range $port := $context.app.port }}
    - protocol: {{ $port.protocol }}
      port: {{ $port.service }}
      targetPort: {{ $port.container }}
{{ end }}