{{ $context := merge (dict "app" $.Values.offlineServer) . -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "neves.name.svc" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  selector:
    app: {{ include "neves.name.app" $context }}
  type: ClusterIP
  ports:
    - name: basic
      protocol: TCP
      port: {{ $context.app.port.service }}
      targetPort: {{ $context.app.port.container }}