{{- $ := .Values.offlineUploadServer -}}
{{- $context := merge (dict "appName" $.appName "component" $.appName) . -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "neves.name.svc" $context }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  type: {{ $.service.type }}
  ports:
    - port: {{ $.service.port }}
      targetPort: {{ $.service.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "neves.name.app" $context | quote }}

