apiVersion: v1
kind: Service
metadata:
  name: offline-upload-server-service
  namespace: neves
spec:
  selector:
    app: offline-upload-server
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8001
    targetPort: 8000

