# user-server-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: {{ .Values.teamName }}
spec:
  selector:
    app: user-server
  ports:
    - protocol: TCP
      name: user-basic
      port: 80
      targetPort: 8000
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800