apiVersion: apps/v1
kind: Deployment
metadata:
  name: play-server
  namespace: {{ .Values.teamName }}
spec:
  replicas: {{ .Values.playServer.replicas }}
  selector:
    matchLabels:
      app: play-server
  template:
    metadata:
      labels:
        app: play-server
    spec:
      containers:
      - name: play-server
        image: {{ printf "%s/%s:%s" .Values.image.root .Values.playServer.image.repo .Values.playServer.image.tag }}
        envFrom:
        - secretRef:
            name: play-server-secret
        - configMapRef:
            name: play-server-config