{{- $context := merge (dict "app" $.Values.playServer) . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "neves.name.configmap" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
{{ with .Values.playServer.config -}}
data:
  CLOUDFRONT_DOMAIN: {{ .cloudFront.domain }}
  CLOUDFRONT_EXPIRE_TIME: {{ .cloudFront.expireTime }}
  CORS_ALLOWED_ORIGINS: {{ .corsAllowedOrigins }}
{{- end -}}