# status-configmap.yaml
{{ if $.Values.statusServer -}}
{{- $context := merge (dict "app" $.Values.statusServer) . -}}
{{- $mailApp := merge (dict "app" $.Values.mailServer) . -}}

{{- include "neves.snipet.cm.header" $context -}}
{{- with .Values.statusServer.config }}
data:
  RDB_URL: {{ printf "jdbc:%s/%s" .db.url .db.name | quote }}
  RDB_DRIVER_CLASS: {{ .db.driver | quote }}
  DB_DDL: {{ .db.ddl | quote }}
  DISCONNECTED_CRON: {{ .disconnectedCron | quote }}
  MAIL_SERVICE_URL: {{ include "neves.svc.path" $mailApp |quote }}
{{ end -}}
{{- end -}}