# persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-shared-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  csi:
    driver: efs.csi.aws.com
    volumeHandle: # EFS 파일 시스템 ID 입력
